version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: notification-service-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5440:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - notification-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: notification-service-migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - notification-service-network
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}",
      "up"
    ]
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile.notificationservice
    container_name: notification-service-app
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      HTTP_PORT: ${HTTP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FILE: ${LOG_FILE}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      USERSERVICE_URL: ${USERSERVICE_URL}
      USERSERVICE_TIMEOUT: ${USERSERVICE_TIMEOUT}
    ports:
      - "8085:8085"
    volumes:
      - ./logs:/app/logs
    networks:
      - notification-service-network
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  notification-service-network:
    driver: bridge
